# CI/CD Azure DevOps deployment pipeline.
# The following variables can be optionally set for each pipeline run:
# - RUN_FLAG_TERRAFORM: Set to 1 to have `terraform apply`. By default
#   `terraform apply` only runs on the master branch.
# - RUN_FLAG_PROMOTE: Set to 1 to promote the Docker image to `latest` tag if
#   tests are successful. By default this is only done on the master branch.
# - RUN_SET_NAMESPACE: Set to a string to deploy to the given AKS namespace,
#   and not delete the namespace after the build. By default the build deploys to
#   the `master` AKS namespace if run on the master branch, and otherwise to a
#   temporary AKS namespace that is deleted at the end of the build.
# - RUN_CREATE_DEMO_KUSTO: Set to 1 to cause the ADX db creation. this is for
#   just for the demo ADX db and should be set only once after a deletion of
#   that DB (which shouldn't normally happen)
stages:

- stage: build
  displayName: Build
  pool:
      # CredScan only runs on Windows
      vmImage: 'ubuntu-16.04'
  jobs:
 
  - job: build_and_unittest
    displayName: Build with UnitTests
    steps:

    - bash: |   
        set -eux  # fail on error
        # Only build first stage of Dockerfile (build and unit test)
        echo $BUILD_SOURCESDIRECTORY\.version\version.txt
        file="$BUILD_SOURCESDIRECTORY/.version/version.txt" #the file where you keep your string name
        name=$(cat "$file")        #the output of 'cat $file' is assigned to the $name variable
        echo $name
        echo "##vso[task.setvariable variable=semanticversion]$name"
        new_version=$(cat .version/version.txt|awk -F "." '{print $1"."$2"."$3+1}')
        echo "$new_version" > .version/version.txt
        echo $(semanticversion)
        

    - bash: |
        cd $(Build.SourcesDirectory)
        git checkout $(Build.SourceBranchName)
        mkdir ~/.ssh
        #key_content=$(echo "$GIT_SSH_PRIVATE_KEY"| sed 's/\-\-\-\-\-BEGIN\ OPENSSH\ PRIVATE\ KEY\-\-\-\-\-\ //g'|sed 's/\ \-\-\-\-\-END\ OPENSSH\ PRIVATE\ KEY\-\-\-\-\-//g'| sed 's/\ /\n/g')
        #echo -e "key content:\n $key_content"
        #echo "-----BEGIN OPENSSH PRIVATE KEY----- " >> ~/.ssh/id_rsa_github
        #echo "$key_content" >> ~/.ssh/id_rsa_github
        #echo -e "-----END OPENSSH PRIVATE KEY-----\n" >> ~/.ssh/id_rsa_github
        echo "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_github
        touch ~/.ssh/config
        echo "host github.com" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  HostName github.com" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa_github" >> ~/.ssh/config
        echo "  User git"  >> ~/.ssh/config
        chmod 400 ~/.ssh/config
        chmod 400 ~/.ssh/id_rsa_github
        ssh -vT git@github.com
        git config --global --add url."git@github.com:".insteadOf "https://github.com/"
        git config user.email "shlavi@microsoft.com" 
        git config user.name "Shiraz Lavi"
        git status
        git add .version/version.txt 
        git commit -m "commit from yml ***NO_CI***"
        git status
        git push
      env:
        GIT_SSH_PRIVATE_KEY: $(GIT_SSH)


    - bash: |   
        echo "docker build --target build --build-arg VersionPrefix=$SEMANTICVERSION -t k2bridge-build ."
        docker build --target build --build-arg VersionPrefix=$SEMANTICVERSION -t k2bridge-build .
        # Temporarily create container in order to extract test results file
        id=$(docker create k2bridge-build)
        docker cp $id:/app/TestResult.xml .
        docker cp $id:/app/K2Bridge.Tests.UnitTests/coverage.cobertura.xml .
        docker rm $id
      displayName: Docker build & test

    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: 'TestResult.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Unit Tests'

    # Publish the code coverage result (summary and web site)
    # The summary allows to view the coverage percentage in the summary tab
    # The web site allows to view which lines are covered directly in Azure Pipeline
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'coverage.cobertura.xml'
        pathToSources: '$(Build.SourcesDirectory)/K2Bridge/'
        failIfCoverageEmpty: true

    - task: AzureCLI@1
      displayName: Login to ACR
      inputs:
        azureSubscription: $(ACR_PUSH_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          set -eux  # fail on error
          az configure --defaults acr="$ACR_NAME"
          az acr login

    - bash: |
        set -eux  # fail on error
        # Build runtime Docker image
        # Reuses the cached build stage from the previous docker build task
        docker build --build-arg VersionPrefix="$SEMANTICVERSION" \
            -t "$ACR_NAME.azurecr.io/k2bridge:$SEMANTICVERSION" \
            .
      displayName: Build Runtime Image

    - bash: |
        set -eux  # fail on error
        # Build e2e-test Docker image
        docker build --target end2endtest \
            --build-arg VersionPrefix="$SEMANTICVERSION" \
            -t "$ACR_NAME.azurecr.io/k2bridge-test:$SEMANTICVERSION" \
            .
      displayName: Build E2E-Test Image

    - task: AzureCLI@1
      displayName: Push Images
      inputs:
        azureSubscription: $(ACR_PUSH_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          set -eux  # fail on error
          # Push Docker image
          docker push "$ACR_NAME.azurecr.io/k2bridge:$SEMANTICVERSION"
          docker push "$ACR_NAME.azurecr.io/k2bridge-test:$SEMANTICVERSION"
          
    - task: HelmInstaller@1
      displayName: Helm installer
      inputs:
        helmVersionToInstall: $(HELM_VERSION)

    - task: AzureCLI@1
      displayName: Push Helm Charts to ACR
      inputs:
        azureSubscription: $(ACR_PUSH_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          # Push Helm chart
          helm repo add elastic https://helm.elastic.co
          helm repo update
          helm dependency update charts/k2bridge
          empty_dir="$(Build.StagingDirectory)/charts_out"
          helm package --version "$SEMANTICVERSION" charts/k2bridge -d $empty_dir
          az acr helm push --force "$(ls $empty_dir/*)"

- stage: integration_tests
  displayName: Integration Tests
  dependsOn:
  - build
  # Deploy a new Kusto db
  # Either if the db name is not set to 'demo' which means it is the Dev CI process
  # Or it is the Demo CI process AND the RUN_CREATE_DEMO_KUSTO was set
  jobs:
  - job: Deploy_Kusto
    displayName: Provision a new Kusto database
    condition: or(and(succeeded(), not(eq(variables['KUSTO_DB'], 'demo'))), and(succeeded(), eq(variables['KUSTO_DB'], 'demo'), variables['RUN_CREATE_DEMO_KUSTO']))
    steps:

        - task: AzureCLI@1
          displayName: Provision Kusto database
          inputs:
            azureSubscription: $(ACR_PULL_SERVICE_CONNECTION)
            scriptLocation: inlineScript
            inlineScript: |
              set -eux  # fail on error
              az kusto database create -g "$(RESOURCE_GROUP)" --cluster-name "$(KUSTO_NAME)" -n "$(KUSTO_DB)"

  - job: Deploy_K2Bridge
    displayName: Deploy K2Bridge
    variables:
      ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
        NOT_MASTER_ES_CONFIG: "--set elasticsearch.replicas=2 --set elasticsearch.minimumMasterNodes=2"
    steps:

    - template: infrastructure/setup-k8s-clients-template.yml

    - task: AzureCLI@1
      displayName: Log into ACR Helm repo
      inputs:
        azureSubscription: $(ACR_PULL_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          set -eu  # fail on error
          az acr helm repo add -n "$(ACR_NAME)"
          KUSTO_URI=$(az kusto cluster show -g $(RESOURCE_GROUP) -n $(KUSTO_NAME) --query uri -o tsv)
          echo "##vso[task.setvariable variable=KUSTO_URI]$KUSTO_URI"

    - bash: |
        set -eux  # fail on error
        helm show chart $(ACR_NAME)/k2bridge
        # List charts before deploying (for job log, useful if rerunning job)
        helm list
        # Deploy chart
        helm upgrade --install k2bridge $(ACR_NAME)/k2bridge \
          --version "$SEMANTICVERSION" \
          --wait --timeout 30m \
          --set image.repository=$(ACR_NAME).azurecr.io/k2bridge \
          --set image.tag=$SEMANTICVERSION \
          --set replicaCount=2 \
          --set settings.adxClusterUrl="$KUSTO_URI" \
          --set settings.adxDefaultDatabaseName="$(KUSTO_DB)" \
          --set settings.aadClientId="$(AKS_SP_CLIENT_ID)" \
          --set settings.aadClientSecret="$secret" \
          --set settings.aadTenantId="$TENANT_ID" \
          --set settings.collectTelemetry="$COLLECT_TELEMETRY" \
          --set settings.instrumentationKey="$TELEMETRY_KEY" \
          --set settings.enableQueryLogging=true \
          ${NOT_MASTER_ES_CONFIG:-} #defaults to an empty string
        # List charts after deploying (for job log)
        helm list
      displayName: Install Helm chart
      env:
        secret: $(AKS_SP_CLIENT_SECRET)

    - bash: |
        set -eux
        kubectl run --attach --rm --restart=Never --image=curlimages/curl smoke-test-$RANDOM -- \
          --max-time 5 --retry 99999 --retry-max-time 1200 http://k2bridge:8080
      displayName: Smoke test

  - job: Deploy_Elasticsearch
    displayName: Deploy Elasticsearch
    steps:

    - template: infrastructure/setup-k8s-clients-template.yml

    - bash: |
        set -eux  # fail on error
        helm list
        helm repo add elastic https://helm.elastic.co
        helm upgrade --install elasticsearchqa elastic/elasticsearch \
          --wait --timeout 45m \
          --set image=docker.elastic.co/elasticsearch/elasticsearch-oss \
          --set imageTag=6.8.5 \
          --set clusterName=elasticsearchqa \
          --set replicas=1 \
          --set persistence.enabled=false \
          --set minimumMasterNodes=1 \
          --set antiAffinity="soft" \
          --set esJavaOpts="-Xmx512m -Xms512m" \
          --set resources.requests.cpu="100m" \
          --set resources.requests.memory="1024M" \
          --set limits.cpu="1000m" \
          --set limits.memory="2048M"

      displayName: Deploy Elasticsearch

  - job: Test
    displayName: Run Tests
    dependsOn:
    - Deploy_Kusto
    - Deploy_K2Bridge
    - Deploy_Elasticsearch
    steps:

    - template: infrastructure/setup-k8s-clients-template.yml

    - task: AzureCLI@1
      displayName: End-to-end test
      inputs:
        azureSubscription: $(ACR_PULL_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          set -eu  # fail on error
          podName="e2e-test-$RANDOM"
          KUSTO_URI=$(az kusto cluster show -g $(RESOURCE_GROUP) -n $(KUSTO_NAME) --query uri -o tsv)
          AAD_TOKEN=$(az account get-access-token --resource "$KUSTO_URI" --query accessToken -o tsv)
          kubectl run --restart=Never \
            --image=$(ACR_NAME).azurecr.io/k2bridge-test:$SEMANTICVERSION \
            --env=K2BRIDGE_URL=http://k2bridge:8080 \
            --env=ELASTICSEARCH_URL=http://elasticsearchqa-master:9200 \
            --env=KUSTO_URI=$KUSTO_URI \
            --env=KUSTO_DB=$(KUSTO_DB) \
            --env=AAD_TOKEN=$AAD_TOKEN \
            "$podName"
          set -x  # enable verbose mode, without exposing $AAD_TOKEN
          kubectl wait --timeout 45m --for=condition=ContainersReady pod "$podName"
          # Read test output from FIFO within container
          kubectl exec "$podName" cat /test-result-pipe > TestResult.xml
          kubectl delete pod "$podName"

    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: 'TestResult.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'E2E Tests'

- stage: cleanup_integration_tests
  displayName: Cleanup Tests
  dependsOn: integration_tests
  # Do not delete AKS namespace:
  # - if pipeline was canceled or failed before a Kubernetes namespace was generated
  # - if deploying on master branch
  # - if namespace was manually set with RUN_SET_NAMESPACE
  condition: and(always(), not(variables['RUN_SET_NAMESPACE']))
  jobs:

  - job: Cleanup
    steps:

    - template: infrastructure/setup-k8s-clients-template.yml

    - task: AzureCLI@1
      displayName: Delete AKS namespace and Kusto database
      condition: and(variables['KUBERNETES_NAMESPACE'], not(eq(variables['KUBERNETES_NAMESPACE'], 'master')))
      inputs:
        azureSubscription: $(ACR_PULL_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          set -eux  # fail on error
          kubectl delete namespace "$KUBERNETES_NAMESPACE"
          az kusto database delete -g "$(RESOURCE_GROUP)" --cluster-name "$(KUSTO_NAME)" -n "$(KUSTO_DB)" -y

- stage: release
  displayName: Release Artifacts
  dependsOn: integration_tests
  jobs:

  - job: Promote
    displayName: Promote Latest Image
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), variables['RUN_FLAG_PROMOTE']))
    steps:

    - task: AzureCLI@1
      displayName: Tag Docker image as latest
      inputs:
        azureSubscription: $(ACR_PUSH_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          set -eux  # fail on error
          az configure --defaults acr="$ACR_NAME"
          az acr login
          docker pull "$ACR_NAME.azurecr.io/k2bridge:$SEMANTICVERSION"
          docker tag \
            "$ACR_NAME.azurecr.io/k2bridge:$SEMANTICVERSION" \
            "$ACR_NAME.azurecr.io/k2bridge:latest"
          docker push "$ACR_NAME.azurecr.io/k2bridge:latest"

    - task: AzureCLI@1
      displayName: Tag Docker image as latest for MCR
      inputs:
        azureSubscription: $(ACR_PUSH_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        inlineScript: |
          set -eux  # fail on error
          az configure --defaults acr="$ACR_MCR_NAME"
          az acr login
          docker pull "$ACR_NAME.azurecr.io/k2bridge:$SEMANTICVERSION"
          docker tag \
            "$ACR_NAME.azurecr.io/k2bridge:$SEMANTICVERSION" \
            "$ACR_MCR_NAME.azurecr.io/public/azuredataexplorer/k2bridge:latest"
          docker push "$ACR_MCR_NAME.azurecr.io/public/azuredataexplorer/k2bridge:latest"
          docker tag \
            "$ACR_NAME.azurecr.io/k2bridge:$SEMANTICVERSION" \
            "$ACR_MCR_NAME.azurecr.io/public/azuredataexplorer/k2bridge:$SEMANTICVERSION"
          docker push "$ACR_MCR_NAME.azurecr.io/public/azuredataexplorer/k2bridge:$SEMANTICVERSION"
